---
name: Meta - Sync labels

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    paths:
      - ".github/labels.yaml"

permissions:
  issues: write

jobs:
  labels:
    name: Sync Labels
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.1
      - name: Sync Labels
        uses: EndBug/label-sync@v2.3.3
        with:
          config-file: .github/labels.yaml
          token: ${{ secrets.GITHUB_TOKEN }}
